# source( "00_preparation.R" )
# source( "01a_generate-random-postcodes.R" )
# source( "01b_save-random-postcodes.R" )
source( "02_map-random-postcodes.R" )
source( "03_generate-synthetic-data.R" )
source( "04_shiny-map.R" )