# source( "00_preparation.R" )
# source( "01a_generate-random-postcodes.R" )
# source( "01b_export-random-postcodes.R" )
# source( "01c_map-random-postcodes.R" )
# source( "02a_obtain_public_data.R" )
# source( "02b_parse-BJP-output.R" )
# source( "03a_parse-ArcPro-output.R" )
# source( "03b_calculate-drivetime-OSRM.R" )
source( "04_compile-final-dataset.R" )
source( "05_generate-synthetic-data.R" )
source( "06a_shiny-map.R" )